version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: bwapp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bWAPP
      MYSQL_USER: bwappuser
      MYSQL_PASSWORD: bwapppass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bwapp_net

  bwapp:
    image: raesene/bwapp
    container_name: bwapp
    restart: always
    ports:
      - "9090:80"
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bWAPP
      MYSQL_USER: bwappuser
      MYSQL_PASSWORD: bwapppass
      MYSQL_HOST: mysql
    networks:
      - bwapp_net

volumes:
  mysql_data:

networks:
  bwapp_net:
    driver: bridge

