services:
  bwapp-mysql:
    image: mysql:5.7
    container_name: bwapp-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  bwapp:
    image: raesene/bwapp
    container_name: bwapp
    restart: always
    ports:
      - "9090:80"
    environment:
      MYSQL_HOST: bwapp-mysql
      MYSQL_DATABASE: bWAPP
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    depends_on:
      - bwapp-mysql

volumes:
  mysql_data:
